### ISSUE TITLE
cleanup/split config- and runtime variables

### ISSUE THREAD

**Issue by shadow974** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#30]
For more readable code, struct_configuration_variables should be split into separate config- and runtime variables. 

Config-Variables should be written to the eeprom if new configuration is pushed by the LCD. 
Runtime-Vars, like ui8_power_regular_state_div25 (assist-level) can be updated many times, without eeprom-writes.

Maybe with a new serial-protocol?

**Comment by sbridger** [comment]
This would be a candidate for literate programming / documentation extraction so that the format documentation (markdown files) and the serial protocol documentation, can be extracted from the source.

With a bit of thought, it could include everything required for a basic (eg phone/pc) UI to be automatically generated - i.e. include the menu strings, defaults, upper/lower limits, help strings

**Comment by leon927** [comment]
@casainho - This is also in a way implemented in the 0.19.0! And only getting better in the 0.20.0! Can be closed!
