### ISSUE TITLE
Stall protection kicks in on startup (0.15.0)

### ISSUE THREAD

**Issue by lightcore-x** [OpenSource-EBike-firmware/TSDZ2-Smart-EBike#50]
Today when driving to work with the new version 0.15.0 I experienced an issue when starting from zero speed. The display shows a blinking 1 and assistance is stopped. This never happens while driving.

You have to stop pedaling for a while to get the assistance back.

My configuration:
- Boost disabled
- 700C / 28" wheel

This is actually a major bug because it's very annoying in daily use, especially in the city.

**Comment by casainho** [comment]
Hmmm, that is because you are pressing the pedals but ebike wheel is not moving...

For me, as I set start up motor without pedaling, that feature protects me, just like that user that did burn the motor because pedal was stuck on the groind doing some torque...
On a stop, I press the pedals AND also press the brake sensors installed, that will not trigger this issue.

Maybe this feature should be disable if startup without pedaling is disable.

**Comment by jbalat** [comment]
Thanks will keep an eye on this I do the same thing

**Comment by AndyME2** [comment]
I incurred a similar experience and i wish i could say what exactly was different from similar situations today when it did not happen..
i do have boost on at startup. it happened that nothing would go when i tried to start to go uphill being already in an inclined position on the  hill. but then, later,  i had 2 or 3 similar situations on a hill where starting was no issue at all. where it did behave as expected, similar to how the stock firmware always did.

**Comment by lightcore-x** [comment]
Should be fixed with release 0.15.1. This issue will be closed after testing.

**Comment by casainho** [comment]
Solved on 0.16.
